language: php

php:
  - 5.6
  - 7.0

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --no-scripts --prefer-source --dev

before_script:
  - cp .env.example .env
  - touch tests/database.sqlite
  - php artisan key:generate
  - php artisan clear-compiled
  - php artisan optimize
  - php artisan cache:clear
  - php artisan migrate --env="testing" --database="sqlite" --force
  - php artisan db:seed --env="testing" --database="sqlite" --force

script: vendor/bin/phpunit

matrix:
  fast_finish: true