<?php

return [

    'login'       => 'fa fa-sign-in',
    'github'      => 'fa fa-github icon',
    'book'        => 'fa fa-book',
    'locale'      => 'fa fa-language',
    'certificate' => 'fa fa-certificate',
    'forum'       => 'fa fa-weixin',
    'logout'      => 'fa fa-sign-out',
    'user'        => 'fa fa-user',
    'plane'       => 'fa fa-paper-plane',
    'check'       => 'fa fa-check',
    'clock'       => 'fa fa-clock-o',
    'tags'        => 'fa fa-tags',
    'comments'    => 'fa fa-comments',
    'reset'       => 'fa fa-refresh',
    'pencil'      => 'fa fa-pencil',
    'delete'      => 'fa fa-trash-o',
    'clip'        => 'fa fa-paperclip',
    'download'    => 'fa fa-cloud-download',
    'dropdown'    => 'fa fa-chevron-down',
    'update'      => 'fa fa-paragraph',
    'reply'       => 'fa fa-reply',
    'preview'     => 'fa fa-code',
    'up'          => 'fa fa-chevron-up',
    'down'        => 'fa fa-chevron-down',
    'filter'      => 'fa fa-filter',
    'view_count'  => 'fa fa-eye',
    'sort'        => 'fa fa-sort',
    'desc'        => 'fa fa-sort-alpha-desc',
    'asc'         => 'fa fa-sort-alpha-asc',
    'new'         => 'fa fa-plus-circle',
    'notice'      => 'fa fa-bullhorn',
    'pin'         => 'fa fa-thumb-tack',

];